### ISSUE TITLE
ERRORS after runing rosrun leap_motion sender.py 

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/leap_motion#50]
terminal 1

mario@mario:~$ sudo leapd
[sudo] password for mario: 
[Info] WebSocket server started
[Info] Secure WebSocket server started
[Info] Leap Motion Controller detected: LP59556685952
[Info] Firmware is up to date.

terminal 2

mario@mario:~$ source ~/catkin_ws/devel/setup.bash && rosrun leap_motion sender.py 

```
Traceback (most recent call last):
  File "/home/mario/catkin_ws/src/leap_motion/scripts/sender.py", line 81, in <module>
    sender()
  File "/home/mario/catkin_ws/src/leap_motion/scripts/sender.py", line 25, in sender
    rospy.loginfo("Parameter set on server: PARAMNAME_FREQ={}".format(rospy.get_param(PARAMNAME_FREQ_ENTIRE, FREQUENCY_ROSTOPIC_DEFAULT)))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 465, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/msproxy.py", line 121, in __getitem__
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
mario@mario:~$ 
```

Thanks a million

**Comment by stevensu1838** [comment]
I forgot to run roscore
